parameters:
    adherent_interests:
        agriculture: Agriculture et pêche
        social: Solidarités
        culture: Culture
        economie: Économie et entreprises
        jeunesse_education: Jeunesse et éducation
        egalite: Égalité femmes-hommes
        emploi: Travail et emploi
        environement: Transition écologique
        europe: Europe
        international: International
        justice: Justice
        numerique: Innovation, recherche et numérique
        sante: Santé
        securite: Sécurité
        sport: Sport
        territoire: Cohésion des territoires
        institution: Institutions et démocratie
